version: "3.8"
services:
  api:
    build:
      context: ./exampleapp
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    restart: always
    networks:
      - example-network
    volumes:
      - ./exampleapp/exampleapp:/app/exampleapp:Z
    command: python manage.py runserver 0.0.0.0:8000

networks:
  example-network:
    driver: bridge
